baseURL = "https://jessejaggars.com/"
languageCode = "en-us"
title = "Jesse Jaggars"
theme = "gohugo-theme-ed"

[params]
  description = 'Personal blog and writings by Jesse Jaggars'
  tagline = 'software engineer and geek'

  # Sections to be displayed in main page and feeds
  mainSections = ['post']

  # Show "Read more" button in list if true
  readmore = true

  showAuthor = true
  [params.author]
    name = 'Jesse Jaggars'
    github = 'jhjaggars'

  [params.social]
    # GitHub username
    github = 'jhjaggars'

[[menu.main]]
  identifier = 'home'
  name = 'Home'
  pageRef = '/'
  weight = 1

[[menu.main]]
  identifier = 'tags'
  name = 'Tags'
  pageRef = '/tags'
  weight = 2

[[menu.main]]
  identifier = 'github'
  name = 'GitHub'
  url = 'https://github.com/jhjaggars'
  weight = 3
  [menu.main.params]
    external = true

[module]
  [[module.imports]]
    path = "github.com/sergeyklay/gohugo-theme-ed"
